// Generated by gencpp from file erp42_msgs/CmdControl.msg
// DO NOT EDIT!


#ifndef ERP42_MSGS_MESSAGE_CMDCONTROL_H
#define ERP42_MSGS_MESSAGE_CMDCONTROL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace erp42_msgs
{
template <class ContainerAllocator>
struct CmdControl_
{
  typedef CmdControl_<ContainerAllocator> Type;

  CmdControl_()
    : MorA(0)
    , EStop(0)
    , Gear(0)
    , KPH(0)
    , Deg(0)
    , brake(0)
    , alive(0)  {
    }
  CmdControl_(const ContainerAllocator& _alloc)
    : MorA(0)
    , EStop(0)
    , Gear(0)
    , KPH(0)
    , Deg(0)
    , brake(0)
    , alive(0)  {
  (void)_alloc;
    }



   typedef uint8_t _MorA_type;
  _MorA_type MorA;

   typedef uint8_t _EStop_type;
  _EStop_type EStop;

   typedef uint8_t _Gear_type;
  _Gear_type Gear;

   typedef uint16_t _KPH_type;
  _KPH_type KPH;

   typedef int16_t _Deg_type;
  _Deg_type Deg;

   typedef uint8_t _brake_type;
  _brake_type brake;

   typedef uint8_t _alive_type;
  _alive_type alive;





  typedef boost::shared_ptr< ::erp42_msgs::CmdControl_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::erp42_msgs::CmdControl_<ContainerAllocator> const> ConstPtr;

}; // struct CmdControl_

typedef ::erp42_msgs::CmdControl_<std::allocator<void> > CmdControl;

typedef boost::shared_ptr< ::erp42_msgs::CmdControl > CmdControlPtr;
typedef boost::shared_ptr< ::erp42_msgs::CmdControl const> CmdControlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::erp42_msgs::CmdControl_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::erp42_msgs::CmdControl_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::erp42_msgs::CmdControl_<ContainerAllocator1> & lhs, const ::erp42_msgs::CmdControl_<ContainerAllocator2> & rhs)
{
  return lhs.MorA == rhs.MorA &&
    lhs.EStop == rhs.EStop &&
    lhs.Gear == rhs.Gear &&
    lhs.KPH == rhs.KPH &&
    lhs.Deg == rhs.Deg &&
    lhs.brake == rhs.brake &&
    lhs.alive == rhs.alive;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::erp42_msgs::CmdControl_<ContainerAllocator1> & lhs, const ::erp42_msgs::CmdControl_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace erp42_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::erp42_msgs::CmdControl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::erp42_msgs::CmdControl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::erp42_msgs::CmdControl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::erp42_msgs::CmdControl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::erp42_msgs::CmdControl_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::erp42_msgs::CmdControl_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::erp42_msgs::CmdControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "17043bad9780a7db1065d8002634203b";
  }

  static const char* value(const ::erp42_msgs::CmdControl_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x17043bad9780a7dbULL;
  static const uint64_t static_value2 = 0x1065d8002634203bULL;
};

template<class ContainerAllocator>
struct DataType< ::erp42_msgs::CmdControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "erp42_msgs/CmdControl";
  }

  static const char* value(const ::erp42_msgs::CmdControl_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::erp42_msgs::CmdControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "########################################\n"
"# Messages\n"
"########################################\n"
"uint8 MorA\n"
"uint8 EStop\n"
"uint8 Gear\n"
"uint16 KPH\n"
"int16 Deg\n"
"uint8 brake\n"
"uint8 alive\n"
"\n"
"\n"
;
  }

  static const char* value(const ::erp42_msgs::CmdControl_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::erp42_msgs::CmdControl_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.MorA);
      stream.next(m.EStop);
      stream.next(m.Gear);
      stream.next(m.KPH);
      stream.next(m.Deg);
      stream.next(m.brake);
      stream.next(m.alive);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CmdControl_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::erp42_msgs::CmdControl_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::erp42_msgs::CmdControl_<ContainerAllocator>& v)
  {
    s << indent << "MorA: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.MorA);
    s << indent << "EStop: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.EStop);
    s << indent << "Gear: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Gear);
    s << indent << "KPH: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.KPH);
    s << indent << "Deg: ";
    Printer<int16_t>::stream(s, indent + "  ", v.Deg);
    s << indent << "brake: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.brake);
    s << indent << "alive: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.alive);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ERP42_MSGS_MESSAGE_CMDCONTROL_H
